# src: .github/workflows/
name: Build and deploy a container to an Azure Container Apps - ACA

env:
  IMAGE_NAME: makremzitoun/devopsrepo
  CONTAINERAPPS_APP: album-backend-api
  CONTAINERAPPS_ENVIRONMENT: aca-environment
  RESOURCE_GROUP: rg-containerapps-github-actions

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  #packages: write  #permision to deploy package on gihub registry

jobs:
  build-push-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
       # uses: docker/login-action@v3
        #with:
         # username: #${{ secrets.DOCKERHUB_USERNAME }}
          #password: #${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: https://hub.docker.com/repository/docker/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          file: ./backend_api_csharp/Dockerfile
          context: ./backend_api_csharp
  
